platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

def flutter_root
  generated = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  raise "#{generated} missing; run `flutter pub get`" unless File.exist?(generated)
  File.foreach(generated) do |l|
    return l.split('=',2)[1].strip if l =~ /FLUTTER_ROOT=/
  end
  raise 'FLUTTER_ROOT not found in Generated.xcconfig'
end

require File.expand_path(
  File.join('packages', 'flutter_tools', 'bin', 'podhelper'),
  flutter_root
)
flutter_ios_podfile_setup    # ← Must appear before any 'target' block

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    flutter_additional_ios_build_settings(t)
  end
end
